name: Data Similarity Check

on:
  push:

env:
  TZ: Asia/Shanghai

jobs:
  data-checker:
    runs-on: ubuntu-latest # [self-hosted]
#    if: ${{ github.actor == 'cherrypan' }}
    steps:
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./requirements.txt
      - name: Run
        run: python3 ./script.py
